server:
  port: 8082

spring:
  application:
    name: common
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: commonService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.62.13.236:3306/jdbc?serverTimezone=Asia/Shanghai
    username: root
    password: nishishui
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  profiles:
    active: